app_name: 'lightMF'
app_listen_host: 'host:port'
app_get_way_host: 'http://my.site/'
db:
    db_name:  'dbname'
    db_user:  'user'
    db_pass:  'pass'
admin_name: 'root'
admin_pass: 'pass'
token_len: 30
session_token_name: 'session_token'
session_token_min: 120
